<?php

if ( ! function_exists( 'icons_lib' ) ) {
    function icons_lib(){
         return array(
            'type' => 'dropdown',
            'heading' => esc_html__( 'Icon library', 'js_composer' ),
            'value' => array(
                'Font Awesome'      => 'fontawesome',
                'Open Iconic'       => 'openiconic',
                'Typicons'          => 'typicons',
                'Entypo'            => 'entypo',
                'Linecons'          => 'linecons',
                'Pixel'             => 'pixelicons',
                'Material'          => 'material',
                'Linea Icons'       => 'lineaicons',
                'IOS7 Stroke Icons' => 'ios7icons',
            ),
            'param_name' => 'icon_type',
            "group" => "Icon",
            'dependency' => array( 'element' => 'use_icon', 'not_empty' => true)
        );
    }
}

if ( ! function_exists( 'icons_lib_ic' ) ) {
    function icons_lib_ic(){
         return array(
            'type' => 'dropdown',
            'heading' => esc_html__( 'Icon library', 'js_composer' ),
            'value' => array(
                'Font Awesome'      => 'fontawesome',
                'Open Iconic'       => 'openiconic',
                'Typicons'          => 'typicons',
                'Entypo'            => 'entypo',
                'Linecons'          => 'linecons',
                'Pixel'             => 'pixelicons',
                'Material'          => 'material',
                'Linea Icons'       => 'lineaicons',
                'IOS7 Stroke Icons' => 'ios7icons',
            ),
            'param_name' => 'icon_type',
            "group" => "Icon",
            'dependency' => array( 'element' => 'icon_typ', 'value' => 'icon')
        );
    }
}

if ( ! function_exists( 'icons_fa' ) ) {
    function icons_fa(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_fontawesome',
            'value' => 'fa fa-star-o',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'fontawesome',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_oc' ) ) {
    function icons_oc(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_openiconic',   
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'openiconic',
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'openiconic',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_ti' ) ) {
    function icons_ti(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_typicons',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'typicons',
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'typicons',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_entypo' ) ) {
    function icons_entypo(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_entypo',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'entypo',
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'entypo',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_line' ) ) {
    function icons_line(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_linecons',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'linecons',
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'linecons',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_px' ) ) {
    function icons_px(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_pixelicons',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'pixelicons',
                'source' => array(
                    array( 'vc_pixel_icon vc_pixel_icon-alert' => esc_html__( 'Alert', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-info' => esc_html__( 'Info', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-tick' => esc_html__( 'Tick', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-explanation' => esc_html__( 'Explanation', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-address_book' => esc_html__( 'Address book', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-alarm_clock' => esc_html__( 'Alarm clock', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-anchor' => esc_html__( 'Anchor', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-application_image' => esc_html__( 'Application Image', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-arrow' => esc_html__( 'Arrow', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-asterisk' => esc_html__( 'Asterisk', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-hammer' => esc_html__( 'Hammer', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-balloon' => esc_html__( 'Balloon', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-balloon_buzz' => esc_html__( 'Balloon Buzz', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-balloon_facebook' => esc_html__( 'Balloon Facebook', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-balloon_twitter' => esc_html__( 'Balloon Twitter', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-battery' => esc_html__( 'Battery', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-binocular' => esc_html__( 'Binocular', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_excel' => esc_html__( 'Document Excel', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_image' => esc_html__( 'Document Image', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_music' => esc_html__( 'Document Music', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_office' => esc_html__( 'Document Office', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_pdf' => esc_html__( 'Document PDF', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_powerpoint' => esc_html__( 'Document Powerpoint', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-document_word' => esc_html__( 'Document Word', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-bookmark' => esc_html__( 'Bookmark', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-camcorder' => esc_html__( 'Camcorder', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-camera' => esc_html__( 'Camera', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-chart' => esc_html__( 'Chart', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-chart_pie' => esc_html__( 'Chart pie', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-clock' => esc_html__( 'Clock', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-fire' => esc_html__( 'Fire', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-heart' => esc_html__( 'Heart', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-mail' => esc_html__( 'Mail', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-play' => esc_html__( 'Play', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-shield' => esc_html__( 'Shield', 'js_composer' ) ),
                    array( 'vc_pixel_icon vc_pixel_icon-video' => esc_html__( 'Video', 'js_composer' ) ),
                ),
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'pixelicons',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_med' ) ) {
    function icons_med(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_lineaicons',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'iconsPerPage' => 4000,
                'type' => 'lineaicons',
                'source' => array(
                    array( "lineaico-uni150" => "" ),
                    array( "lineaico-uni151" => "" ),
                    array( "lineaico-uni152" => "" ),
                    array( "lineaico-uni153" => "" ),
                    array( "lineaico-uni154" => "" ),
                    array( "lineaico-uni155" => "" ),
                    array( "lineaico-uni156" => "" ),
                    array( "lineaico-uni157" => "" ),
                    array( "lineaico-uni158" => "" ),
                    array( "lineaico-uni159" => "" ),
                    array( "lineaico-uni15A" => "" ),
                    array( "lineaico-uni15B" => "" ),
                    array( "lineaico-uni15C" => "" ),
                    array( "lineaico-uni15D" => "" ),
                    array( "lineaico-uni15E" => "" ),
                    array( "lineaico-uni15F" => "" ),
                    array( "lineaico-uni160" => "" ),
                    array( "lineaico-uni161" => "" ),
                    array( "lineaico-uni162" => "" ),
                    array( "lineaico-uni163" => "" ),
                    array( "lineaico-uni164" => "" ),
                    array( "lineaico-uni165" => "" ),
                    array( "lineaico-uni166" => "" ),
                    array( "lineaico-uni167" => "" ),
                    array( "lineaico-uni168" => "" ),
                    array( "lineaico-uni169" => "" ),
                    array( "lineaico-uni16A" => "" ),
                    array( "lineaico-uni16B" => "" ),
                    array( "lineaico-uni16C" => "" ),
                    array( "lineaico-uni16D" => "" ),
                    array( "lineaico-uni16E" => "" ),
                    array( "lineaico-uni16F" => "" ),
                    array( "lineaico-uni170" => "" ),
                    array( "lineaico-uni171" => "" ),
                    array( "lineaico-uni172" => "" ),
                    array( "lineaico-uni173" => "" ),
                    array( "lineaico-uni174" => "" ),
                    array( "lineaico-uni175" => "" ),
                    array( "lineaico-uni176" => "" ),
                    array( "lineaico-uni177" => "" ),
                    array( "lineaico-uni178" => "" ),
                    array( "lineaico-uni179" => "" ),
                    array( "lineaico-uni17A" => "" ),
                    array( "lineaico-uni17B" => "" ),
                    array( "lineaico-uni17C" => "" ),
                    array( "lineaico-uni17D" => "" ),
                    array( "lineaico-uni17E" => "" ),
                    array( "lineaico-uni17F" => "" ),
                    array( "lineaico-uni180" => "" ),
                    array( "lineaico-uni181" => "" ),
                    array( "lineaico-uni182" => "" ),
                    array( "lineaico-uni183" => "" ),
                    array( "lineaico-uni184" => "" ),
                    array( "lineaico-uni185" => "" ),
                    array( "lineaico-uni186" => "" ),
                    array( "lineaico-uni187" => "" ),
                    array( "lineaico-uni188" => "" ),
                    array( "lineaico-uni189" => "" ),
                    array( "lineaico-uni18A" => "" ),
                    array( "lineaico-uni18B" => "" ),
                    array( "lineaico-uni18C" => "" ),
                    array( "lineaico-uni18D" => "" ),
                    array( "lineaico-uni18E" => "" ),
                    array( "lineaico-uni18F" => "" ),
                    array( "lineaico-uni190" => "" ),
                    array( "lineaico-uni191" => "" ),
                    array( "lineaico-uni192" => "" ),
                    array( "lineaico-uni193" => "" ),
                    array( "lineaico-uni194" => "" ),
                    array( "lineaico-uni195" => "" ),
                    array( "lineaico-uni196" => "" ),
                    array( "lineaico-uni197" => "" ),
                    array( "lineaico-uni198" => "" ),
                    array( "lineaico-uni199" => "" ),
                    array( "lineaico-uni19A" => "" ),
                    array( "lineaico-uni19B" => "" ),
                    array( "lineaico-uni19C" => "" ),
                    array( "lineaico-uni19D" => "" ),
                    array( "lineaico-uni19E" => "" ),
                    array( "lineaico-uni19F" => "" ),
                    array( "lineaico-uni1A0" => "" ),
                    array( "lineaico-uni1A1" => "" ),
                    array( "lineaico-uni1A2" => "" ),
                    array( "lineaico-uni1A3" => "" ),
                    array( "lineaico-uni1A4" => "" ),
                    array( "lineaico-uni1A5" => "" ),
                    array( "lineaico-uni1A6" => "" ),
                    array( "lineaico-uni1A7" => "" ),
                    array( "lineaico-uni1A8" => "" ),
                    array( "lineaico-uni1A9" => "" ),
                    array( "lineaico-uni1AA" => "" ),
                    array( "lineaico-uni1AB" => "" ),
                    array( "lineaico-uni1AC" => "" ),
                    array( "lineaico-uni1AD" => "" ),
                    array( "lineaico-uniE116" => "" ),
                    array( "lineaico-uniE117" => "" ),
                    array( "lineaico-uniE118" => "" ),
                    array( "lineaico-uniE119" => "" ),
                    array( "lineaico-uniE11A" => "" ),
                    array( "lineaico-uniE11B" => "" ),
                    array( "lineaico-uniE11C" => "" ),
                    array( "lineaico-uniE11D" => "" ),
                    array( "lineaico-uniE11E" => "" ),
                    array( "lineaico-uniE11F" => "" ),
                    array( "lineaico-uniE120" => "" ),
                    array( "lineaico-uniE121" => "" ),
                    array( "lineaico-uniE122" => "" ),
                    array( "lineaico-uniE123" => "" ),
                    array( "lineaico-uniE124" => "" ),
                    array( "lineaico-uniE125" => "" ),
                    array( "lineaico-uniE126" => "" ),
                    array( "lineaico-uniE127" => "" ),
                    array( "lineaico-uniE128" => "" ),
                    array( "lineaico-uniE129" => "" ),
                    array( "lineaico-uniE12A" => "" ),
                    array( "lineaico-uniE12B" => "" ),
                    array( "lineaico-uniE12C" => "" ),
                    array( "lineaico-uniE12D" => "" ),
                    array( "lineaico-uniE12E" => "" ),
                    array( "lineaico-uniE12F" => "" ),
                    array( "lineaico-uniE130" => "" ),
                    array( "lineaico-uniE131" => "" ),
                    array( "lineaico-uniE132" => "" ),
                    array( "lineaico-uniE133" => "" ),
                    array( "lineaico-uniE134" => "" ),
                    array( "lineaico-uniE135" => "" ),
                    array( "lineaico-uniE136" => "" ),
                    array( "lineaico-uniE137" => "" ),
                    array( "lineaico-uniE138" => "" ),
                    array( "lineaico-uniE139" => "" ),
                    array( "lineaico-uniE13A" => "" ),
                    array( "lineaico-uniE13B" => "" ),
                    array( "lineaico-uniE13C" => "" ),
                    array( "lineaico-uniE13D" => "" ),
                    array( "lineaico-uniE13E" => "" ),
                    array( "lineaico-uniE13F" => "" ),
                    array( "lineaico-uniE130" => "" ),
                    array( "lineaico-uniE131" => "" ),
                    array( "lineaico-uniE132" => "" ),
                    array( "lineaico-uniE133" => "" ),
                    array( "lineaico-uniE134" => "" ),
                    array( "lineaico-uniE135" => "" ),
                    array( "lineaico-uniE136" => "" ),
                    array( "lineaico-uniE137" => "" ),
                    array( "lineaico-uniE138" => "" ),
                    array( "lineaico-uniE139" => "" ),
                    array( "lineaico-uniE13A" => "" ),
                    array( "lineaico-uniE13B" => "" ),
                    array( "lineaico-uniE13C" => "" ),
                    array( "lineaico-uniE13D" => "" ),
                    array( "lineaico-uniE13E" => "" ),
                    array( "lineaico-uniE08E" => "" ),
                    array( "lineaico-uniE08F" => "" ),
                    array( "lineaico-uniE090" => "" ),
                    array( "lineaico-uniE091" => "" ),
                    array( "lineaico-uniE092" => "" ),
                    array( "lineaico-uniE093" => "" ),
                    array( "lineaico-uniE094" => "" ),
                    array( "lineaico-uniE095" => "" ),
                    array( "lineaico-uniE096" => "" ),
                    array( "lineaico-uniE097" => "" ),
                    array( "lineaico-uniE098" => "" ),
                    array( "lineaico-uniE099" => "" ),
                    array( "lineaico-uniE09A" => "" ),
                    array( "lineaico-uniE09B" => "" ),
                    array( "lineaico-uniE09C" => "" ),
                    array( "lineaico-uniE09D" => "" ),
                    array( "lineaico-uniE09E" => "" ),
                    array( "lineaico-uniE09F" => "" ),
                    array( "lineaico-uniE0A0" => "" ),
                    array( "lineaico-uniE0A1" => "" ),
                    array( "lineaico-uniE0A2" => "" ),
                    array( "lineaico-uniE0A3" => "" ),
                    array( "lineaico-uniE0A4" => "" ),
                    array( "lineaico-uniE0A5" => "" ),
                    array( "lineaico-uniE0A6" => "" ),
                    array( "lineaico-uniE0A7" => "" ),
                    array( "lineaico-uniE0A8" => "" ),
                    array( "lineaico-uniE0A9" => "" ),
                    array( "lineaico-uniE0AA" => "" ),
                    array( "lineaico-uniE0AB" => "" ),
                    array( "lineaico-uniE0AC" => "" ),
                    array( "lineaico-uniE0AD" => "" ),
                    array( "lineaico-uniE0AE" => "" ),
                    array( "lineaico-uniE0AF" => "" ),
                    array( "lineaico-uniE0B0" => "" ),
                    array( "lineaico-uniE0B1" => "" ),
                    array( "lineaico-uniE0B2" => "" ),
                    array( "lineaico-uniE0B3" => "" ),
                    array( "lineaico-uniE0B4" => "" ),
                    array( "lineaico-uniE0B5" => "" ),
                    array( "lineaico-uniE0B6" => "" ),
                    array( "lineaico-uniE0B7" => "" ),
                    array( "lineaico-uniE0B8" => "" ),
                    array( "lineaico-uniE0B9" => "" ),
                    array( "lineaico-uniE0BA" => "" ),
                    array( "lineaico-uniE0BB" => "" ),
                    array( "lineaico-uniE0BC" => "" ),
                    array( "lineaico-uniE0BD" => "" ),
                    array( "lineaico-uniE0BE" => "" ),
                    array( "lineaico-uniE0BF" => "" ),
                    array( "lineaico-uniE0C0" => "" ),
                    array( "lineaico-uniE0C1" => "" ),
                    array( "lineaico-uniE0C2" => "" ),
                    array( "lineaico-uniE0C3" => "" ),
                    array( "lineaico-uniE0C4" => "" ),
                    array( "lineaico-uniE0C5" => "" ),
                    array( "lineaico-uniE0C6" => "" ),
                    array( "lineaico-uniE0C7" => "" ),
                    array( "lineaico-uniE0C8" => "" ),
                    array( "lineaico-uniE0C9" => "" ),
                    array( "lineaico-uniE0CA" => "" ),
                    array( "lineaico-uniE0CB" => "" ),
                    array( "lineaico-uniE0CC" => "" ),
                    array( "lineaico-uniE0CD" => "" ),
                    array( "lineaico-uniE0CE" => "" ),
                    array( "lineaico-uniE0CF" => "" ),
                    array( "lineaico-uniE0D0" => "" ),
                    array( "lineaico-uniE0D1" => "" ),
                    array( "lineaico-uniE0D2" => "" ),
                    array( "lineaico-uniE0D3" => "" ),
                    array( "lineaico-uniE0D4" => "" ),
                    array( "lineaico-uniE0D5" => "" ),
                    array( "lineaico-uniE0D6" => "" ),
                    array( "lineaico-uniE0D7" => "" ),
                    array( "lineaico-uniE0D8" => "" ),
                    array( "lineaico-uniE0D9" => "" ),
                    array( "lineaico-uniE0DA" => "" ),
                    array( "lineaico-uniE0DB" => "" ),
                    array( "lineaico-uniE0DC" => "" ),
                    array( "lineaico-uniE0DD" => "" ),
                    array( "lineaico-uniE0DE" => "" ),
                    array( "lineaico-uniE0DF" => "" ),
                    array( "lineaico-uniE0E0" => "" ),
                    array( "lineaico-uniE0E1" => "" ),
                    array( "lineaico-uniE0E2" => "" ),
                    array( "lineaico-uniE0E3" => "" ),
                    array( "lineaico-uniE0E4" => "" ),
                    array( "lineaico-uniE0E5" => "" ),
                    array( "lineaico-uniE0E6" => "" ),
                    array( "lineaico-uniE0E7" => "" ),
                    array( "lineaico-uniE0E8" => "" ),
                    array( "lineaico-uniE0E9" => "" ),
                    array( "lineaico-uniE0EA" => "" ),
                    array( "lineaico-uniE0EB" => "" ),
                    array( "lineaico-uniE0EC" => "" ),
                    array( "lineaico-uniE0ED" => "" ),
                    array( "lineaico-uniE0EE" => "" ),
                    array( "lineaico-uniE0EF" => "" ),
                    array( "lineaico-uniE0F0" => "" ),
                    array( "lineaico-uniE0F1" => "" ),
                    array( "lineaico-uniE0F2" => "" ),
                    array( "lineaico-uniE0F3" => "" ),
                    array( "lineaico-uniE0F4" => "" ),
                    array( "lineaico-uniE0F5" => "" ),
                    array( "lineaico-uniE0F6" => "" ),
                    array( "lineaico-uniE0F7" => "" ),
                    array( "lineaico-uniE0F8" => "" ),
                    array( "lineaico-uniE0F9" => "" ),
                    array( "lineaico-uniE0FA" => "" ),
                    array( "lineaico-uniE0FB" => "" ),
                    array( "lineaico-uniE0FC" => "" ),
                    array( "lineaico-uniE0FD" => "" ),
                    array( "lineaico-uniE0FE" => "" ),
                    array( "lineaico-uniE0FF" => "" ),
                    array( "lineaico-uniE100" => "" ),
                    array( "lineaico-uniE101" => "" ),
                    array( "lineaico-uniE102" => "" ),
                    array( "lineaico-uniE103" => "" ),
                    array( "lineaico-uniE104" => "" ),
                    array( "lineaico-uniE105" => "" ),
                    array( "lineaico-uniE106" => "" ),
                    array( "lineaico-uniE107" => "" ),
                    array( "lineaico-uniE108" => "" ),
                    array( "lineaico-uniE109" => "" ),
                    array( "lineaico-uniE10A" => "" ),
                    array( "lineaico-uniE10B" => "" ),
                    array( "lineaico-uniE10C" => "" ),
                    array( "lineaico-uniE10D" => "" ),
                    array( "lineaico-uniE10E" => "" ),
                    array( "lineaico-uniE10F" => "" ),
                    array( "lineaico-uniE110" => "" ),
                    array( "lineaico-uniE111" => "" ),
                    array( "lineaico-uniE112" => "" ),
                    array( "lineaico-uniE113" => "" ),
                    array( "lineaico-uniE114" => "" ),
                    array( "lineaico-uniE115" => "" ),
                    array( "lineaico-uniE116" => "" ),
                    array( "lineaico-uniE117" => "" ),
                    array( "lineaico-uniE118" => "" ),
                    array( "lineaico-uniE119" => "" ),
                    array( "lineaico-uniE11A" => "" ),
                    array( "lineaico-uniE11B" => "" ),
                    array( "lineaico-uniE11C" => "" ),
                    array( "lineaico-uniE11D" => "" ),
                    array( "lineaico-uniE11E" => "" ),
                    array( "lineaico-uniE11F" => "" ),
                    array( "lineaico-uniE110" => "" ),
                    array( "lineaico-uniE111" => "" ),
                    array( "lineaico-uniE112" => "" ),
                    array( "lineaico-uniE113" => "" ),
                    array( "lineaico-uniE114" => "" ),
                    array( "lineaico-uniE115" => "" ),
                    array( "lineaico-uniA0" => "" ),
                    array( "lineaico-uniA1" => "" ),
                    array( "lineaico-uniA2" => "" ),
                    array( "lineaico-uniA3" => "" ),
                    array( "lineaico-uniA4" => "" ),
                    array( "lineaico-uniA5" => "" ),
                    array( "lineaico-uniA6" => "" ),
                    array( "lineaico-uniA7" => "" ),
                    array( "lineaico-uniA8" => "" ),
                    array( "lineaico-uniA9" => "" ),
                    array( "lineaico-uniAA" => "" ),
                    array( "lineaico-uniAB" => "" ),
                    array( "lineaico-uniAC" => "" ),
                    array( "lineaico-uniAE" => "" ),
                    array( "lineaico-uniAF" => "" ),
                    array( "lineaico-uniB0" => "" ),
                    array( "lineaico-uniB1" => "" ),
                    array( "lineaico-uniB2" => "" ),
                    array( "lineaico-uniB3" => "" ),
                    array( "lineaico-uniB4" => "" ),
                    array( "lineaico-uniB5" => "" ),
                    array( "lineaico-uniB6" => "" ),
                    array( "lineaico-uniB7" => "" ),
                    array( "lineaico-uniB8" => "" ),
                    array( "lineaico-uniB9" => "" ),
                    array( "lineaico-uniBA" => "" ),
                    array( "lineaico-uniBB" => "" ),
                    array( "lineaico-uniBC" => "" ),
                    array( "lineaico-uniBD" => "" ),
                    array( "lineaico-uniBE" => "" ),
                    array( "lineaico-uniBF" => "" ),
                    array( "lineaico-uniC0" => "" ),
                    array( "lineaico-uniC1" => "" ),
                    array( "lineaico-uniC2" => "" ),
                    array( "lineaico-uniC3" => "" ),
                    array( "lineaico-uniC4" => "" ),
                    array( "lineaico-uniC5" => "" ),
                    array( "lineaico-uniC6" => "" ),
                    array( "lineaico-uniC7" => "" ),
                    array( "lineaico-uniC8" => "" ),
                    array( "lineaico-uniC9" => "" ),
                    array( "lineaico-uniCA" => "" ),
                    array( "lineaico-uniCB" => "" ),
                    array( "lineaico-uniCC" => "" ),
                    array( "lineaico-uniCD" => "" ),
                    array( "lineaico-uniCE" => "" ),
                    array( "lineaico-uniCF" => "" ),
                    array( "lineaico-uniD0" => "" ),
                    array( "lineaico-uniD1" => "" ),
                    array( "lineaico-uniD2" => "" ),
                    array( "lineaico-uniD3" => "" ),
                    array( "lineaico-uniD4" => "" ),
                    array( "lineaico-uniD5" => "" ),
                    array( "lineaico-uniD6" => "" ),
                    array( "lineaico-uniD7" => "" ),
                    array( "lineaico-uniD8" => "" ),
                    array( "lineaico-uniD9" => "" ),
                    array( "lineaico-uniDA" => "" ),
                    array( "lineaico-uniDB" => "" ),
                    array( "lineaico-uniDC" => "" ),
                    array( "lineaico-uniDD" => "" ),
                    array( "lineaico-uniDE" => "" ),
                    array( "lineaico-uniDF" => "" ),
                    array( "lineaico-uniE0" => "" ),
                    array( "lineaico-uniE1" => "" ),
                    array( "lineaico-uniE2" => "" ),
                    array( "lineaico-uniE3" => "" ),
                    array( "lineaico-uniE4" => "" ),
                    array( "lineaico-uniE5" => "" ),
                    array( "lineaico-uniE6" => "" ),
                    array( "lineaico-uniE7" => "" ),
                    array( "lineaico-uniE8" => "" ),
                    array( "lineaico-uniE9" => "" ),
                    array( "lineaico-uniEA" => "" ),
                    array( "lineaico-uniEB" => "" ),
                    array( "lineaico-uniEC" => "" ),
                    array( "lineaico-uniED" => "" ),
                    array( "lineaico-uniEE" => "" ),
                    array( "lineaico-uniEF" => "" ),
                    array( "lineaico-uniF0" => "" ),
                    array( "lineaico-uniF1" => "" ),
                    array( "lineaico-uniF2" => "" ),
                    array( "lineaico-uniF3" => "" ),
                    array( "lineaico-uniF4" => "" ),
                    array( "lineaico-uniF5" => "" ),
                    array( "lineaico-uniF6" => "" ),
                    array( "lineaico-uniF7" => "" ),
                    array( "lineaico-uniF8" => "" ),
                    array( "lineaico-uniF9" => "" ),
                    array( "lineaico-uniFA" => "" ),
                    array( "lineaico-uniE088" => "" ),
                    array( "lineaico-uniE089" => "" ),
                    array( "lineaico-uniE08A" => "" ),
                    array( "lineaico-uniE08B" => "" ),
                    array( "lineaico-uniE08C" => "" ),
                    array( "lineaico-uniE08D" => "" ),
                    array( "lineaico-uniFB" => "" ),
                    array( "lineaico-uniFC" => "" ),
                    array( "lineaico-uniFD" => "" ),
                    array( "lineaico-uniFE" => "" ),
                    array( "lineaico-uniFF" => "" ),
                    array( "lineaico-uni100" => "" ),
                    array( "lineaico-uni101" => "" ),
                    array( "lineaico-uni102" => "" ),
                    array( "lineaico-uni103" => "" ),
                    array( "lineaico-uni104" => "" ),
                    array( "lineaico-uni105" => "" ),
                    array( "lineaico-uni106" => "" ),
                    array( "lineaico-uni107" => "" ),
                    array( "lineaico-uni108" => "" ),
                    array( "lineaico-uni109" => "" ),
                    array( "lineaico-uni10A" => "" ),
                    array( "lineaico-uni10B" => "" ),
                    array( "lineaico-uni10C" => "" ),
                    array( "lineaico-uni10D" => "" ),
                    array( "lineaico-uni10E" => "" ),
                    array( "lineaico-uni10F" => "" ),
                    array( "lineaico-uni110" => "" ),
                    array( "lineaico-uni111" => "" ),
                    array( "lineaico-uni112" => "" ),
                    array( "lineaico-uni113" => "" ),
                    array( "lineaico-uni114" => "" ),
                    array( "lineaico-uni115" => "" ),
                    array( "lineaico-uni116" => "" ),
                    array( "lineaico-uni117" => "" ),
                    array( "lineaico-uni118" => "" ),
                    array( "lineaico-uni119" => "" ),
                    array( "lineaico-uni11A" => "" ),
                    array( "lineaico-uni11B" => "" ),
                    array( "lineaico-uni11C" => "" ),
                    array( "lineaico-uni11D" => "" ),
                    array( "lineaico-uni11E" => "" ),
                    array( "lineaico-uni11F" => "" ),
                    array( "lineaico-uni120" => "" ),
                    array( "lineaico-uni121" => "" ),
                    array( "lineaico-uni122" => "" ),
                    array( "lineaico-uni123" => "" ),
                    array( "lineaico-uni124" => "" ),
                    array( "lineaico-uni125" => "" ),
                    array( "lineaico-uni126" => "" ),
                    array( "lineaico-uni127" => "" ),
                    array( "lineaico-uni128" => "" ),
                    array( "lineaico-uni129" => "" ),
                    array( "lineaico-uni12A" => "" ),
                    array( "lineaico-uni12B" => "" ),
                    array( "lineaico-uni12C" => "" ),
                    array( "lineaico-uni12D" => "" ),
                    array( "lineaico-uni12E" => "" ),
                    array( "lineaico-uni12F" => "" ),
                    array( "lineaico-uni130" => "" ),
                    array( "lineaico-uni131" => "" ),
                    array( "lineaico-uni132" => "" ),
                    array( "lineaico-uni133" => "" ),
                    array( "lineaico-uni134" => "" ),
                    array( "lineaico-uni135" => "" ),
                    array( "lineaico-uni136" => "" ),
                    array( "lineaico-uni137" => "" ),
                    array( "lineaico-uni138" => "" ),
                    array( "lineaico-uni139" => "" ),
                    array( "lineaico-uni13A" => "" ),
                    array( "lineaico-uni13B" => "" ),
                    array( "lineaico-uni13C" => "" ),
                    array( "lineaico-uni13D" => "" ),
                    array( "lineaico-uni13E" => "" ),
                    array( "lineaico-uni13F" => "" ),
                    array( "lineaico-uni140" => "" ),
                    array( "lineaico-uni141" => "" ),
                    array( "lineaico-uni142" => "" ),
                    array( "lineaico-uni143" => "" ),
                    array( "lineaico-uni144" => "" ),
                    array( "lineaico-uni145" => "" ),
                    array( "lineaico-uni146" => "" ),
                    array( "lineaico-uni147" => "" ),
                    array( "lineaico-uni148" => "" ),
                    array( "lineaico-uni149" => "" ),
                    array( "lineaico-uni14A" => "" ),
                    array( "lineaico-uni14B" => "" ),
                    array( "lineaico-uni14C" => "" ),
                    array( "lineaico-uni14D" => "" ),
                    array( "lineaico-uni14E" => "" ),
                    array( "lineaico-uni14F" => "" ),
                    array( "lineaico-uniE033" => "" ),
                    array( "lineaico-uniE034" => "" ),
                    array( "lineaico-uniE035" => "" ),
                    array( "lineaico-uniE036" => "" ),
                    array( "lineaico-uniE037" => "" ),
                    array( "lineaico-uniE038" => "" ),
                    array( "lineaico-uniE039" => "" ),
                    array( "lineaico-uniE03A" => "" ),
                    array( "lineaico-uniE03B" => "" ),
                    array( "lineaico-uniE03C" => "" ),
                    array( "lineaico-uniE03D" => "" ),
                    array( "lineaico-uniE03E" => "" ),
                    array( "lineaico-uniE03F" => "" ),                            
                ),
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'lineaicons',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_ios7' ) ) {
    function icons_ios7(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_ios7icons',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'iconsPerPage' => 4000,
                'type' => 'ios7icons',
                'source' => array(
                    array( "pe-7s-album" => "" ),
                    array( "pe-7s-arc" => "" ),
                    array( "pe-7s-back-2" => "" ),
                    array( "pe-7s-bandaid" => "" ),
                    array( "pe-7s-car" => "" ),
                    array( "pe-7s-diamond" => "" ),
                    array( "pe-7s-door-lock" => "" ),
                    array( "pe-7s-eyedropper" => "" ),
                    array( "pe-7s-female" => "" ),
                    array( "pe-7s-gym" => "" ),
                    array( "pe-7s-hammer" => "" ),
                    array( "pe-7s-headphones" => "" ),
                    array( "pe-7s-helm" => "" ),
                    array( "pe-7s-hourglass" => "" ),
                    array( "pe-7s-leaf" => "" ),
                    array( "pe-7s-magic-wand" => "" ),
                    array( "pe-7s-male" => "" ),
                    array( "pe-7s-map-2" => "" ),
                    array( "pe-7s-next-2" => "" ),
                    array( "pe-7s-paint-bucket" => "" ),
                    array( "pe-7s-pendrive" => "" ),
                    array( "pe-7s-photo" => "" ),
                    array( "pe-7s-piggy" => "" ),
                    array( "pe-7s-plugin" => "" ),
                    array( "pe-7s-refresh-2" => "" ),
                    array( "pe-7s-rocket" => "" ),
                    array( "pe-7s-settings" => "" ),
                    array( "pe-7s-shield" => "" ),
                    array( "pe-7s-smile" => "" ),
                    array( "pe-7s-usb" => "" ),
                    array( "pe-7s-vector" => "" ),
                    array( "pe-7s-wine" => "" ),
                    array( "pe-7s-cloud-upload" => "" ),
                    array( "pe-7s-cash" => "" ),
                    array( "pe-7s-close" => "" ),
                    array( "pe-7s-bluetooth" => "" ),
                    array( "pe-7s-cloud-download" => "" ),
                    array( "pe-7s-way" => "" ),
                    array( "pe-7s-close-circle" => "" ),
                    array( "pe-7s-id" => "" ),
                    array( "pe-7s-angle-up" => "" ),
                    array( "pe-7s-wristwatch" => "" ),
                    array( "pe-7s-angle-up-circle" => "" ),
                    array( "pe-7s-world" => "" ),
                    array( "pe-7s-angle-right" => "" ),
                    array( "pe-7s-volume" => "" ),
                    array( "pe-7s-angle-right-circle" => "" ),
                    array( "pe-7s-users" => "" ),
                    array( "pe-7s-angle-left" => "" ),
                    array( "pe-7s-user-female" => "" ),
                    array( "pe-7s-angle-left-circle" => "" ),
                    array( "pe-7s-up-arrow" => "" ),
                    array( "pe-7s-angle-down" => "" ),
                    array( "pe-7s-switch" => "" ),
                    array( "pe-7s-angle-down-circle" => "" ),
                    array( "pe-7s-scissors" => "" ),
                    array( "pe-7s-wallet" => "" ),
                    array( "pe-7s-safe" => "" ),
                    array( "pe-7s-volume2" => "" ),
                    array( "pe-7s-volume1" => "" ),
                    array( "pe-7s-voicemail" => "" ),
                    array( "pe-7s-video" => "" ),
                    array( "pe-7s-user" => "" ),
                    array( "pe-7s-upload" => "" ),
                    array( "pe-7s-unlock" => "" ),
                    array( "pe-7s-umbrella" => "" ),
                    array( "pe-7s-trash" => "" ),
                    array( "pe-7s-tools" => "" ),
                    array( "pe-7s-timer" => "" ),
                    array( "pe-7s-ticket" => "" ),
                    array( "pe-7s-target" => "" ),
                    array( "pe-7s-sun" => "" ),
                    array( "pe-7s-study" => "" ),
                    array( "pe-7s-stopwatch" => "" ),
                    array( "pe-7s-star" => "" ),
                    array( "pe-7s-speaker" => "" ),
                    array( "pe-7s-signal" => "" ),
                    array( "pe-7s-shuffle" => "" ),
                    array( "pe-7s-shopbag" => "" ),
                    array( "pe-7s-share" => "" ),
                    array( "pe-7s-server" => "" ),
                    array( "pe-7s-search" => "" ),
                    array( "pe-7s-film" => "" ),
                    array( "pe-7s-science" => "" ),
                    array( "pe-7s-disk" => "" ),
                    array( "pe-7s-ribbon" => "" ),
                    array( "pe-7s-repeat" => "" ),
                    array( "pe-7s-refresh" => "" ),
                    array( "pe-7s-add-user" => "" ),
                    array( "pe-7s-refresh-cloud" => "" ),
                    array( "pe-7s-paperclip" => "" ),
                    array( "pe-7s-radio" => "" ),
                    array( "pe-7s-note2" => "" ),
                    array( "pe-7s-print" => "" ),
                    array( "pe-7s-network" => "" ),
                    array( "pe-7s-prev" => "" ),
                    array( "pe-7s-mute" => "" ),
                    array( "pe-7s-power" => "" ),
                    array( "pe-7s-medal" => "" ),
                    array( "pe-7s-portfolio" => "" ),
                    array( "pe-7s-like2" => "" ),
                    array( "pe-7s-plus" => "" ),
                    array( "pe-7s-left-arrow" => "" ),
                    array( "pe-7s-play" => "" ),
                    array( "pe-7s-key" => "" ),
                    array( "pe-7s-plane" => "" ),
                    array( "pe-7s-joy" => "" ),
                    array( "pe-7s-photo-gallery" => "" ),
                    array( "pe-7s-pin" => "" ),
                    array( "pe-7s-phone" => "" ),
                    array( "pe-7s-plug" => "" ),
                    array( "pe-7s-pen" => "" ),
                    array( "pe-7s-right-arrow" => "" ),
                    array( "pe-7s-paper-plane" => "" ),
                    array( "pe-7s-delete-user" => "" ),
                    array( "pe-7s-paint" => "" ),
                    array( "pe-7s-bottom-arrow" => "" ),
                    array( "pe-7s-notebook" => "" ),
                    array( "pe-7s-note" => "" ),
                    array( "pe-7s-next" => "" ),
                    array( "pe-7s-news-paper" => "" ),
                    array( "pe-7s-musiclist" => "" ),
                    array( "pe-7s-music" => "" ),
                    array( "pe-7s-mouse" => "" ),
                    array( "pe-7s-more" => "" ),
                    array( "pe-7s-moon" => "" ),
                    array( "pe-7s-monitor" => "" ),
                    array( "pe-7s-micro" => "" ),
                    array( "pe-7s-menu" => "" ),
                    array( "pe-7s-map" => "" ),
                    array( "pe-7s-map-marker" => "" ),
                    array( "pe-7s-mail" => "" ),
                    array( "pe-7s-mail-open" => "" ),
                    array( "pe-7s-mail-open-file" => "" ),
                    array( "pe-7s-magnet" => "" ),
                    array( "pe-7s-loop" => "" ),
                    array( "pe-7s-look" => "" ),
                    array( "pe-7s-lock" => "" ),
                    array( "pe-7s-lintern" => "" ),
                    array( "pe-7s-link" => "" ),
                    array( "pe-7s-like" => "" ),
                    array( "pe-7s-light" => "" ),
                    array( "pe-7s-less" => "" ),
                    array( "pe-7s-keypad" => "" ),
                    array( "pe-7s-junk" => "" ),
                    array( "pe-7s-info" => "" ),
                    array( "pe-7s-home" => "" ),
                    array( "pe-7s-help2" => "" ),
                    array( "pe-7s-help1" => "" ),
                    array( "pe-7s-graph3" => "" ),
                    array( "pe-7s-graph2" => "" ),
                    array( "pe-7s-graph1" => "" ),
                    array( "pe-7s-graph" => "" ),
                    array( "pe-7s-global" => "" ),
                    array( "pe-7s-gleam" => "" ),
                    array( "pe-7s-glasses" => "" ),
                    array( "pe-7s-gift" => "" ),
                    array( "pe-7s-folder" => "" ),
                    array( "pe-7s-flag" => "" ),
                    array( "pe-7s-filter" => "" ),
                    array( "pe-7s-file" => "" ),
                    array( "pe-7s-expand1" => "" ),
                    array( "pe-7s-exapnd2" => "" ),
                    array( "pe-7s-edit" => "" ),
                    array( "pe-7s-drop" => "" ),
                    array( "pe-7s-drawer" => "" ),
                    array( "pe-7s-download" => "" ),
                    array( "pe-7s-display2" => "" ),
                    array( "pe-7s-display1" => "" ),
                    array( "pe-7s-diskette" => "" ),
                    array( "pe-7s-date" => "" ),
                    array( "pe-7s-cup" => "" ),
                    array( "pe-7s-culture" => "" ),
                    array( "pe-7s-crop" => "" ),
                    array( "pe-7s-credit" => "" ),
                    array( "pe-7s-copy-file" => "" ),
                    array( "pe-7s-config" => "" ),
                    array( "pe-7s-compass" => "" ),
                    array( "pe-7s-comment" => "" ),
                    array( "pe-7s-coffee" => "" ),
                    array( "pe-7s-cloud" => "" ),
                    array( "pe-7s-clock" => "" ),
                    array( "pe-7s-check" => "" ),
                    array( "pe-7s-chat" => "" ),
                    array( "pe-7s-cart" => "" ),
                    array( "pe-7s-camera" => "" ),
                    array( "pe-7s-call" => "" ),
                    array( "pe-7s-calculator" => "" ),
                    array( "pe-7s-browser" => "" ),
                    array( "pe-7s-box2" => "" ),
                    array( "pe-7s-box1" => "" ),
                    array( "pe-7s-bookmarks" => "" ),
                    array( "pe-7s-bicycle" => "" ),
                    array( "pe-7s-bell" => "" ),
                    array( "pe-7s-battery" => "" ),
                    array( "pe-7s-ball" => "" ),
                    array( "pe-7s-back" => "" ),
                    array( "pe-7s-attention" => "" ),
                    array( "pe-7s-anchor" => "" ),
                    array( "pe-7s-albums" => "" ),
                    array( "pe-7s-alarm" => "" ),
                    array( "pe-7s-airplay" => "" ),
                )
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'ios7icons',
            ),
        );    
    }
}

if ( ! function_exists( 'icons_material' ) ){
    function icons_material(){
        return array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'js_composer' ),
            'param_name' => 'icon_material',
            "group" => "Icon",
            'settings' => array(
                'emptyIcon' => false,
                'type' => 'material',
                'iconsPerPage' => 4000,
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'material',
            ),
        );    
    }
}